language: node_js

node_js:
  - "0.12"
  

addons:
  sauce_connect: true

services:
  - mongodb

sudo: required

before_install:
  - "npm install -g grunt-cli bower"
  - "gem install sass --version 3.4.0"
  - "bower install"
  - "export SAUCE_USERNAME=maxkarel"
  - "export SAUCE_ACCESS_KEY=65c152b4-7218-45a6-ac8b-6908c9755ce3"
  # Add demo01 data
  - "./tools/setupData.sh demo01"

before_script:
  - "./node_modules/.bin/webdriver-manager update"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
