language: node_js

node_js:
  - "0.12"


addons:
  sauce_connect:
      username: "maxkarel"
      access_key: "65c152b4-7218-45a6-ac8b-6908c9755ce3"

services:
  - mongodb

sudo: required

before_install:

  - "gem install sass --version 3.4.0"
  - "git clone https://github.com/membery/engine"
  # "./init.sh"

before_script:
  - "export DISPLAY=:99.0"
  - "sleep 3"
